---
- name: "Deploy bspwm vm"
  hosts: bspwm
  become: true
  vars:
    ansible_host: "10.0.5.9"
  tasks:
    - name: Post vm clone tasks
      ansible.builtin.include_role:
        role: post-vm-clone
      vars:
        reboot: true
        distro: "arch"

    - name: "Install arch distro x base"
      ansible.builtin.include_role:
        name: install-arch-x-base
      vars:
        yay_srcdir: /tmp

    - name: "Install packages"
      kewlfft.aur.aur:
        use: yay
        update_cache: true
        name:
          - bspwm
          - sxhkd
          - rxvt-unicode
        state: present
