---
- name: "Deploy bspwm vm"
  hosts: bspwm
  vars:
    ansible_host: "10.0.5.9"
    yay_srcdir: /tmp
  tasks:
    - name: Post vm clone tasks
      ansible.builtin.include_role:
        role: post_vm_clone
      vars:
        reboot: true
        distro: "arch"

    - name: Install arch distro x base
      ansible.builtin.include_role:
        name: install_arch_x_base

    - name: Install arch distro x base
      ansible.builtin.include_role:
        name: install_pipewire_audio

    - name: Install packages
      kewlfft.aur.aur:
        use: yay
        update_cache: true
        name:
          - bspwm
          - sxhkd
          - rxvt-unicode
          # - picom
          # - polybar
          - rofi
        state: present
