---
- name: "Configure bspwm base"
  hosts: bspwm-jankvisor
  vars:
    yay_srcdir: /tmp
  tasks:
    - name: Post vm clone tasks
      ansible.builtin.include_role:
        role: post_vm_clone
      vars:
        reboot: true
        distro: "arch"

    - name: Install arch distro common
      ansible.builtin.include_role:
        name: common

    - name: Install arch distro graphics common
      ansible.builtin.include_role:
        name: arch_graphic_common

    - name: Install arch distro x base
      ansible.builtin.include_role:
        name: install_arch_x_base

    - name: Install packages
      kewlfft.aur.aur:
        use: yay
        update_cache: true
        name:
          - bspwm
          - sxhkd
          - rxvt-unicode
          # - picom
          # - polybar
          - rofi
        state: present

    - name: Add static ips
      community.general.nmcli:
        conn_name: "{{ item.key }}"
        ifname: "{{ item.key }}"
        type: ethernet
        ip4: "{{ item.value['ip'] }}"
        gw4: "{{ item.value['gateway'] | default(omit) }}"
        dns4: "{{ item.value['dns'] | default(omit) }}"
        state: present
      loop: "{{ interfaces | dict2items }}"
      become: true

- name: "Configure bspwm user"
  hosts: bspwm
  vars:
    ansible_ssh_user: "{{ guest_username }}"
  tasks:
    - name: Run chezmoi
      ansible.builtin.include_role:
        name: run_chezmoi
