---
- name: Check if yay exists
  ansible.builtin.stat:
    path: /usr/bin/yay
  register: st

- name: Make, clone, and build yay
  when: not st.stat.exists
  block:

    - name: Make yay build dir
      ansible.builtin.file:
        path: "{{ yay_srcdir }}/yay"
        state: directory
        owner: ansible
        group: ansible
        mode: '0700'
      become: true

    - name: Clone yay # noqa latest[git]
      ansible.builtin.git:
        repo: https://aur.archlinux.org/yay-bin.git
        dest: "{{ yay_srcdir }}/yay/"
        update: true

    - name: Build and install yay
      ansible.builtin.command:
        chdir: "{{ yay_srcdir }}/yay"
        cmd: "makepkg -sfi --noconfirm"
        creates: /usr/bin/yay
