---
- name: Add apt sources for {{ customisation.name }}
  ansible.builtin.include_tasks:
    apply:
      tags: wanix_apt
    file: add_apt_source.yml
  when: customisation.apt_sources is defined
  loop: "{{ customisation.apt_sources }}"
  loop_control:
    loop_var: "source"
  tags: wanix_apt

- name: Install apt Packages for {{ customisation.name }}
  ansible.builtin.apt:
    name: "{{ customisation.packages }}"
    state: present
    update_cache: true
    install_recommends: false
  when: customisation.packages is defined
  tags: wanix_apt

- name: Install pip Packages for {{ customisation.name }}
  become_user: ripple
  become: true
  ansible.builtin.pip:
    name: "{{ customisation.pip_packages }}"
    extra_args: --user --break-system-packages
  when: customisation.pip_packages is defined
  tags: wanix_pip

- name: Run roles for {{ customisation.name }}
  ansible.builtin.include_role:
    apply:
      tags: wanix_roles
    name: "{{ role }}"
  when: customisation.roles is defined
  loop: "{{ customisation.roles }}"
  loop_control:
    loop_var: "role"
  tags: wanix_roles
