---
- name: Including customizations
  ansible.builtin.debug:
    msg: "{{ wanix_include_customizations + wanix_default_customizations + wanix_extra_customizations }}"


- name: Include distro specific customizations
  ansible.builtin.include_tasks:

    file: "{{ ansible_facts['os_family'] }}_customize.yml"
  when: customization.name in wanix_include_customizations + wanix_default_customizations + wanix_extra_customizations
  loop: "{{ wanix_customizations | customizations_flattener(ansible_facts['os_family']) }}"
  loop_control:
    loop_var: customization

- name: Run dotfile manager dotman
  ansible.builtin.include_role:
    name: dotman
  vars:
    dotman_installed_packages: "{{ wanix_customizations | cd_package_extractor(wanix_include_customizations + wanix_default_customizations + wanix_extra_customizations, ansible_facts['os_family']) }}"
    dotman_installed_custiomizations: "{{ wanix_include_customizations + wanix_default_customizations + wanix_extra_customizations }}"
    dotman_file_destinations: "{{ wanix_file_destinations }}"
    dotman_file_depmap: "{{ wanix_file_depmap }}"
    dotman_file_copys: "{{ wanix_file_copys }}"
