---
- name: "Install packages"
  kewlfft.aur.aur:
    use: yay
    update_cache: true
    name:
      - xorg
      - xorg-xinit
      - xterm
      - nitrogen
      - polybar

- name: Add x related chezmoi config
  ansible.builtin.copy:
    dest: "/home/{{ guest_username }}/.config/chezmoi/chezmoi.yml"
    content: |
      data:
        isX: true
    owner: "{{ guest_username }}"
    group: "{{ guest_username }}"
    mode: "0644"
  become: true
