- name: Check if user is lingering
  ansible.builtin.stat:
    path: "/var/lib/systemd/linger/{{ userdata.username }}"
  register: user_lingering

- name: Enable lingering if needed
  ansible.builtin.command: "loginctl enable-linger {{ userdata.username }}"
  when: not user_lingering.stat.exists and "linger" in userdata and userdata.linger
  changed_when: not user_lingering.stat.exists
