---
- name: Run distro specific zsh install
  ansible.builtin.include_tasks:
    file: "{{ ansible_facts['os_family'] }}.yml"

- name: Check if omz exists
  ansible.builtin.stat:
    path: /home/{{ guest_username }}/.oh-my-zsh
  register: st
  become: true

- name: install zsh and omz
  when: not st.stat.exists
  block:

    - name: clone oh my zsh
      become: true
      ansible.builtin.git:
        repo: https://github.com/ohmyzsh/ohmyzsh.git
        dest: /home/{{ guest_username }}/.oh-my-zsh


    - name: Set default shell for users
      become: true
      ansible.builtin.user:
        name: '{{ guest_username }}'
        shell: '/bin/zsh'

    - name: clone p10k
      become: true
      ansible.builtin.git:
        repo: https://github.com/romkatv/powerlevel10k.git
        dest: /home/{{ guest_username }}/.oh-my-zsh/custom/themes/powerlevel10k

    - name: clone plugins
      become: true
      ansible.builtin.git:
        repo: "{{ item.value }}"
        dest: /home/{{ guest_username }}/.oh-my-zsh/custom/plugins/{{ item.key }}
      with_dict: "{{ omz_plugins }}"

    - name: Set oh my zsh perms
      become: true
      ansible.builtin.file:
        path: "/home/{{ guest_username }}/.oh-my-zsh"
        mode: 'go-w'
        owner: "{{ guest_username }}"
        group: "{{ guest_username }}"
        recurse: true
