---
- name: Install pipewire
  ansible.builtin.apt:
    name:
      - pipewire
      - libspa-0.2-bluetooth
      - pipewire-alsa
      - pipewire-jack
      - pipewire-audio
      - wireplumber
      - pipewire-pulse

- name: Enable wireplumber server
  become: true
  become_user: ripple
  ansible.builtin.systemd:
    name: wireplumber.service
    scope: user
    enabled: true
    state: started
