- name: Install packages
  kewlfft.aur.aur:
    use: yay
    extra_args:
    name:
      - pipewire
      - pipewire-audio
      - pipewire-alsa
      - pipewire-pulse
      - pavucontrol
      - python-setuptools
      - python-pexpect

- name: Install wireplumber
  ansible.builtin.expect:
    command: "yay -S --needed --cleanafter wireplumber --nodeps"
    responses:
      (?i)wireplumber and pipewire-media-session are in conflict.*:
        - y
      installation:
        - y
    creates: /usr/bin/wireplumber
