---
- name: Check if user is lingering
  ansible.builtin.stat:
    path: "/var/lib/systemd/linger/ripple"
  register: user_lingering

- name: Enable lingering is needed
  ansible.builtin.command: "loginctl enable-linger ripple"
  when: not user_lingering.stat.exists

- name: Run distro specific config
  ansible.builtin.include_tasks:
    file: "{{ ansible_facts['os_family'] }}.yml"
