- name: Install nmcli
  kewlfft.aur.aur:
    use: yay
    update_cache: true
    name: network-manager
    state: "present"

- name: Start network manager service
  ansible.builtin.systemd:
    name: NetworkManager
    state: "started"
    enabled: true

- name: Disable dhcpd
  ansible.builtin.systemd:
    name: "dhcpcd@{{ interface_name }}"
    enabled: false
