- name: Check if provision happened
  ansible.builtin.stat:
    path: /etc/provisioned
  register: st

- name: Run post clone
  when: not st.stat.exists
  block:
    - name: Update /etc/hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        regexp: '^(127.0.1.1.*)$'
        line: "127.0.1.1\t{{ hostname }}.{{ domain }}\t{{ hostname }}" # noqa no-tabs

    - name: Reset machine ID # noqa no-free-form
      ansible.builtin.shell:
        cmd: |
          rm -f /etc/machine-id /var/lib/dbus/machine-id &&
          dbus-uuidgen --ensure=/etc/machine-id &&
          dbus-uuidgen --ensure
      changed_when: true

    - name: Perform os dependent config
      ansible.builtin.include_tasks:
        file: "{{ ansible_facts['os_family'] }}.yml"

    - name: Set hostname
      ansible.builtin.hostname:
        name: "{{ hostname }}"
        use: systemd

    - name: Add stat file
      ansible.builtin.file:
        path: /etc/provisioned
        state: touch
        mode: "0644"
