install_zsh_plugins:
  zsh-autocomplete: https://github.com/marlonrichert/zsh-autocomplete.git
  zsh-autosuggestions: https://github.com/zsh-users/zsh-autosuggestions.git
  zsh-syntax-highlighting: https://github.com/zsh-users/zsh-syntax-highlighting.git
