wanix_customisations:
  - name: setup_uwusers
    roles:
      - setup_uwusers
      - setup_private_ssh_keys

  - name: wanix_base_tools
    roles:
      - name: install_git
      - name: install_yay
        deb_install: false

  - name: post_vm_clone
    roles:
      - post_clone_setup

  - name: setup_base_environment
    packages:
      - linux-headers
      - python-pip

  - name: nmcli_networking
    packages:
      - networkmanager
    roles:
      - setup_nmcli

  - name: cli_base_tools
    packages:
      - bind
      - nano
      - nmap
      - unzip
      - curl
      - neofetch
      - calc
      - zsh

    roles:
      - name: configure_omzsh


  - name: cli_dev_tools
    packages:
      - packer
      - terraform
      - sshpass
      - direnv
      - docker
    roles:
      - name: install_bsm
        provides_pkgs:
          - bsm

  - name: nvidia_drivers
    packages:
      - nvidia-vaapi-driver
      - nvidia-driver
      - firmware-misc-nonfree

  - name: x_server
    packages:
      - xorg
      - xinit

  - name: graphical_common
    packages:
      - firefox
      - sddm
      - gnome-font-viewer
      - gsfonts

    roles:
      - name: setup_sddm

  - name: graphical_dev
    packages:
      - visual-studio-code-bin

  - name: graphical_social
    packages:
      - discord

  - name: graphical_sound
    packages:
      - easyeffects
      - pavucontrol
      - spotify-launcher

  - name: pipewire_sound_server
    roles:
      - name: install_pipewire_audio
        provides_pkgs:
          - pipewire

  - name: meaditha
    packages:
      - bspwm
      - sxhkd
      - polybar
      - rofi
      - nitrogen
      - dunst
      - rxvt-unicode
      - imagemagick
      - kitty
      - python-gobject

    pip_packages:
      - pycairo
      - escrotum
      - name: pywal16
        install: git+https://github.com/eylles/pywal16

    roles:
      - add_fonts

  - name: configure_extra_disks
    packages:
      - btrfs-progs
      - open-iscsi
    roles:
      - configure_iscsi_disks
      - setup_fstab

  - name: old_af_gpu_patch
    roles:
      - old_af_gpu_patch

