---
- name: Create ssh dir
  ansible.builtin.file:
    path: /home/ripple/.ssh
    state: directory
    owner: "ripple"
    group: "ripple"
    mode: "0700"
  become: true

- name: Set user's public ssh key
  ansible.builtin.copy:
    dest: "/home/ripple/.ssh/id_ed25519.pub"
    content: "{{ lookup('ansible.builtin.file', 'ripple/id_ed25519.pub') }}"
    mode: '0644'
    owner: "ripple"
    group: "ripple"
  become: true

- name: Set user's private ssh key
  ansible.builtin.copy:
    dest: "/home/ripple/.ssh/id_ed25519"
    content: "{{ lookup('community.general.bitwarden_secrets_manager', 'd8f06df6-f274-4f96-a87d-b0a3017b0c18').value }}"
    mode: '0600'
    owner: "ripple"
    group: "ripple"
  no_log: true
  become: true

- name: Set users autherised ssh key
  ansible.posix.authorized_key:
    user: ripple
    state: present
    key: "{{ lookup('ansible.builtin.file', 'ripple/id_ed25519.pub') }}"
