---
- name: Run distro specific config
  ansible.builtin.include_tasks:
    file: "{{ ansible_facts['os_family'] }}.yml"

- name: Run post distro specific config
  ansible.builtin.include_tasks:
    file: "posttasks.yml"
