---
- name: Enable service docker
  ansible.builtin.service:
    name: docker
    enabled: true
  become: true

- name: Add user to docker group
  ansible.builtin.user:
    user: "{{ guest_username }}"
    groups: docker
    append: true
  become: true

- name: Install bsm keys
  ansible.builtin.include_role:
    name: install_bsm

- name: Create chezmoi config file
  ansible.builtin.file:
    path: /home/{{ guest_username }}/.config/chezmoi/
    state: directory
    owner: "{{ guest_username }}"
    group: "{{ guest_username }}"
    mode: "0744"
  become: true

- name: Install zsh
  ansible.builtin.include_role:
    name: install_zsh

- name: Install ssh keys
  ansible.builtin.include_role:
    name: setup_ssh_keys
