---

- name: Install pulseaudio
  ansible.builtin.apt:
    name: pulseaudio
    state: present

- name: Start pulseaudio
  become: true
  become_user: vmaudio
  become_method: su
  ansible.builtin.systemd_service:
    name: pulseaudio
    state: started
    scope: user
    masked: false
  environment:
    XDG_RUNTIME_DIR: "/run/user/1000"

- name: Setup pulseaudio socket
  ansible.builtin.lineinfile:
    dest: "/etc/pulse/default.pa"
    state: present
    line: "load-module module-native-protocol-unix auth-anonymous=1 socket=/tmp/pulse-socket"
    regexp: "^load-module module-native-protocol-unix"

- name: Setup pulseaudio dissable idle time
  ansible.builtin.lineinfile:
    dest: "/etc/pulse/daemon.conf"
    state: present
    line: "exit-idle-time = -1"
    regexp: "^exit-idle-time = -1"

