all:
  hosts:
  children:
    iscsi_hosts:
      hosts:
        jankvisor-iscsi
    wanix_machines:
      children:
        wanix_vms:
          children:
            meaditha:
              hosts:
                meaditha-arch:
        wanix_bearmetal:
          hosts:
            jankvisor:
              ansible_host: 10.0.1.30
              ansible_ssh_user: root
    primary:
      hosts:
        meaditha-arch:
