---
- name: Initialize chezmoi
  ansible.builtin.command:
    chdir: /home/ripple/
    cmd: "chezmoi init --apply git@github.com:rippleFCL/dotfiles.git"
    creates: "/home/{{ guest_username }}/.local/share/chezmoi/"
