---
- name: Initialize chezmoi
  become_user: ripple
  become: true
  ansible.builtin.shell:
    chdir: /home/ripple/
    cmd: "set -o pipefail && curl -fsLS get.chezmoi.io | sh -s -- -b .local/bin/ init --apply https://github.com/rippleFCL/dotfiles.git"
    creates: "/home/ripple/.local/share/chezmoi/"
  args:
    executable: /usr/bin/bash
