- name: "Install packages"
  kewlfft.aur.aur:
    use: yay
    extra_args:
    name:
      - pipewire
      - pipewire-audio
      - pipewire-alsa
      - pipewire-pulse
      - pavucontrol
      - python-setuptools
      - python-pexpect

- name: "Install wireplumber"
  ansible.builtin.expect:
    command: "yay -S --needed --cleanafter wireplumber --nodeps"
    responses:
      installation:
        - y
      pipewire-media-session:
        - y
