
- name: Create home dirs
  ansible.builtin.file:
    path: /home/{{ guest_username }}/{{ item }}
    state: directory
    owner: "{{ guest_username }}"
    group: "{{ guest_username }}"
    mode: "0744"
  loop: "{{ home_dirs }}"
  become: true

- name: Enable sddm
  ansible.builtin.systemd:
    name: sddm
    enabled: true
  become: true

- name: Install pipewasdire audio packages
  ansible.builtin.include_role:
    name: install_pipewire_audio