---
- name: Including customisations
  ansible.builtin.debug:
    msg: "{{ wanix_include_customisations + wanix_default_customisations + wanix_extra_customisations }}"

- name: Include distro specific customisations
  ansible.builtin.include_tasks:
    file: "{{ ansible_facts['os_family'] }}_customize.yml"
  when: customisation.name in wanix_include_customisations + wanix_default_customisations + wanix_extra_customisations
  loop: "{{ wanix_customisations | customisations_flattener(ansible_facts['os_family']) }}"
  loop_control:
    loop_var: customisation

- name: Run dotfile manager wanix_dotman
  ansible.builtin.include_role:
    name: wanix_dotman
  vars:
    wanix_dotman_installed_packages: "{{ wanix_customisations | cd_package_extractor(wanix_include_customisations + wanix_default_customisations + wanix_extra_customisations, ansible_facts['os_family']) }}"
    wanix_dotman_installed_custiomizations: "{{ wanix_include_customisations + wanix_default_customisations + wanix_extra_customisations }}"
    wanix_dotman_file_destinations: "{{ wanix_file_destinations }}"
    wanix_dotman_file_depmap: "{{ wanix_file_depmap }}"
    wanix_dotman_file_copys: "{{ wanix_file_copys }}"

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
