ansible_user_password: ENC[AES256_GCM,data:672TuV0Mh0mzor5Po0I6MV4P83VHwW7EIg==,iv:kPlYVrmMYQrrG0hXGzUJdmjNX8PI/hEyZjKI4lFFGok=,tag:N6xLQxa9JSJMnFgDaQBNiQ==,type:str]
default_user_password: ENC[AES256_GCM,data:nl3HWQs1O50DE9QFUKg83A==,iv:qZ0PKcbvBO125QzPv5vBXfIK/UxMgCizx2mTm8+Y5Mo=,tag:aWqGTOQ5csxWSygtH7L7eA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fsd3qafhdzqd6mfyyuv8wddlzg6tcgy28gfxa9fpkk68y0084agq70dwh0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1bVl4YXVOS1lWdFFjWitr
            ZWYwL3Z3bjRkL040VGxKazdkVW1RRDJ4c2prCkkvYXlRbVRDcXdRVjJzSW94ZE82
            cXpHbzFvMmVOM3FCci9Zc1ZWMUFtYncKLS0tIEV5djVLY1dPb3JaMEpLWlh5UHZ0
            RVNPU0NxaXc4eXB5VlFmeTNUSXdrUE0Kesmj2PDNDa2AwBFrr1xi7Ap8inva+VVg
            wlypP3SwTUFzv+Jx9tnybVTQ3LxSi6ZJ9nrTupAhSMMsxF69uTo1MQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-16T21:05:21Z"
    mac: ENC[AES256_GCM,data:W5jBL0vyJ61xxECzlRikJJ8S3Sna0rlpkDkhFDNorOXVgGHLnoDxechkjpitSNG2Gi+9nwpT9DHym060V6NJ73vs69VRA0XA5OuQEFGzSa4iDpX+TjYrBChSchC1oF17GdNz2ZfNmQ+GnXrMI7P4AsivhQRxK99B9raQXiilut8=,iv:ATeKNZAvVsCT+H/IPmwR80oe4BklOIIJKEnqFZeikyk=,tag:uG4CASA5f3S0J9I8S6bT6g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
