cpu_manufacturer: 'amd'
vfio_pci_ids:
  - 10de:2489
  - 10de:228b
  - 10de:2187
  - 10de:1aeb
  - 10de:1aec
  - 10de:1aed

linux_cmdline_extra_args: "quiet resume=UUID=c754ede5-c0ae-4bd1-bac6-62b143dfd8d6 resume_offset=9934848"

usbinfo:
  primary:
    - "5-2.1"
    - "5-2.2"
    - "5-2.3"
  secondary:
    - "5-1.1"
    - "5-1.2"
    - "5-1.3"

pcieinfo:
  primary:
    - "0000:03:00"
  secondary:
    - "0000:0a:00"

networkinfo:
  primary:
    - mac: CA:13:80:09:EA:7B
      bridge: vmbr0
      firewall: 1
      tag: 70
    - mac: CA:13:80:09:EA:7C
      bridge: vmbr0
      firewall: 1
      tag: 10
    - mac: CA:13:80:09:EA:7D
      bridge: vmbr0
      firewall: 1
      tag: null

  secondary:
    - mac: 62:03:E8:5C:92:35
      bridge: vmbr0
      firewall: 1
      tag: 70
    - mac: 62:03:E8:5C:92:36
      bridge: vmbr0
      firewall: 1
      tag: 10
    - mac: 62:03:E8:5C:92:37
      bridge: vmbr0
      firewall: 1
      tag: null

cpuinfo:
  primary: 32
  secondary: 32

memoryinfo:
  primary: 12000
  secondary: 16000

audioinfo:
  primary:
    - type: duplex
      output: bluez_sink.00_14_41_2F_17_19.a2dp_sink
      input: alsa_input.usb-Focusrite_Scarlett_Solo_USB_Y7K6EZV2B73C1D-00.analog-stereo
    - type: output
      output: alsa_output.usb-Focusrite_Scarlett_Solo_USB_Y7K6EZV2B73C1D-00.analog-stereo
  secondary:
    - type: duplex
      output: bluez_sink.00_14_41_2F_17_19.a2dp_sink
      input: alsa_input.usb-Focusrite_Scarlett_Solo_USB_Y7K6EZV2B73C1D-00.analog-stereo
    - type: output
      output: alsa_output.usb-Focusrite_Scarlett_Solo_USB_Y7K6EZV2B73C1D-00.analog-stereo
      input: null