vfio_pci_ids:
  - 10de:2489
  - 10de:228b
  - 10de:2187
  - 10de:1aeb
  - 10de:1aec
  - 10de:1aed

linux_cmdline_args:
  - quiet
  - amd_iommu=on
  - iommu=pt
  - vfio_pci.disable_vga=1
  - initcall_blacklist=sysfb_init
  - pcie_acs_override=downstream,multifunction

ansible_connection: local
