- name: Install git
  community.general.pacman:
    name: git
    state: present
  become: true

- name: Ensure github.com is a known host
  become: true
  ansible.builtin.lineinfile:
    dest: "/home/{{ guest_username }}/.ssh/known_hosts"
    create: true
    state: present
    group: "{{ guest_username }}"
    owner: "{{ guest_username }}"
    line: "{{ lookup('pipe', 'ssh-keyscan -t ' + item + ' github.com') }}"
    mode: "0600"
    regexp: "^github\\.com {{ item }}"
  loop: ["ecdsa-sha2-nistp256", "ssh-ed25519", "ssh-rsa"]

- name: Add safe directorys
  community.general.git_config:
    name: safe.directory
    value: "*"
  become: true

- name: Install yay
  ansible.builtin.include_role:
    name: install_yay

- name: "Install common packages "
  kewlfft.aur.aur:
    use: yay
    update_cache: true
    name:
      # - ansible
      - chezmoi
      - direnv
      - docker
      - docker-compose
      - nano
      - neofetch
      - nerd-fonts-complete
      - nmap
      - packer
      - python-pip
      - ttf-jetbrains-mono-nerd
      - ttf-maple
      - ttf-maple-sc-nerd
      - ttf-nerd-fonts-symbols-mono
      - unzip
      - terraform
      - sshpass
      - go
      - duplicity

- name: Enable service docker
  ansible.builtin.service:
    name: docker
    enabled: true
  become: true

- name: Add user to docker group
  ansible.builtin.user:
    user: "{{ guest_username }}"
    groups: docker
    append: true
  become: true

- name: Install bsm keys
  ansible.builtin.include_role:
    name: install_bsm


- name: Create chezmoi config file
  ansible.builtin.file:
    path: /home/{{ guest_username }}/.config/chezmoi/
    state: directory
    owner: "{{ guest_username }}"
    group: "{{ guest_username }}"
    mode: "0744"
  become: true


- name: Install zsh
  ansible.builtin.include_role:
    name: install_zsh

- name: Install ssh keys
  ansible.builtin.include_role:
    name: setup_ssh_keys
