- name: Install git
  community.general.pacman:
    name: git
    state: present
  become: true

- name: ensure github.com is a known host
  become: true
  ansible.builtin.lineinfile:
    dest: "/home/{{ guest_username }}/.ssh/known_hosts"
    create: yes
    state: present
    group: "{{ guest_username }}"
    owner: "{{ guest_username }}"
    line: "{{ lookup('pipe', 'ssh-keyscan -t ed25519 github.com') }}"
    regexp: "^github\\.com"

- name: Add safe directorys
  community.general.git_config:
    name: safe.directory
    value: "*"
  become: true

- name: Install yay
  ansible.builtin.include_role:
    name: install_yay

- name: "Install common packages "
  kewlfft.aur.aur:
    use: yay
    update_cache: true
    name:
     - nano
     - ttf-jetbrains-mono-nerd
     - ttf-nerd-fonts-symbols-mono
     - ttf-maple
     - ttf-maple-sc-nerd
     - nerd-fonts-complete
     - chezmoi
     - direnv
     - ansible
     - packer
     - docker
     - docker-compose
     - neofetch
     - unzip
     - python-pip


- name: Enable service docker
  ansible.builtin.service:
    name: docker
    enabled: true
  become: true

- name: Add user to docker group
  ansible.builtin.user:
    user: "{{ guest_username }}"
    groups: docker
    append: true
  become: true

- name: Install bsm keys
  ansible.builtin.include_role:
    name: install_bsm


- name: Create chezmoi config file
  ansible.builtin.file:
    path: /home/{{ guest_username }}/.config/chezmoi/
    state: directory
    owner: "{{ guest_username }}"
    group: "{{ guest_username }}"
    mode: "0744"
  become: true


- name: Install zsh
  ansible.builtin.include_role:
    name: install_zsh

- name: Install ssh keys
  ansible.builtin.include_role:
    name: setup_ssh_keys
