---
- name: "Copy private keys to user directory"
  no_log: false
  ansible.builtin.copy:
    dest: "{{ user.directory }}/id_{{ item.key_type }}"
    content: "{{ item.content }}\n"
    mode: "0600"
    owner: "{{ user.username }}"
    group: "{{ user.username }}"
  loop: "{{ user.private_keys }}"
  loop_control:
    label: "{{ item.key_type }}"

- name: "Copy public keys to user directory"
  ansible.builtin.copy:
    dest: "{{ user.directory }}/id_{{ item.key_type }}.pub"
    content: "{{ item.content }}\n"
    mode: "0644"
    owner: "{{ user.username }}"
    group: "{{ user.username }}"
  loop: "{{ user.public_keys }}"
