- name: "Configure jankvisors base configuration"
  hosts: jankvisor
  vars_prompt:
    - name: org_id
      prompt: What is your org id?
      private: false
  tasks:
    - name: Install docker
      ansible.builtin.include_role:
        name: geerlingguy.docker

    - name: Run bws-cache
      ansible.builtin.include_role:
        name: bws_cache

    - name: Setup uwusers
      ansible.builtin.include_role:
        name: setup_uwusers

    - name: Setup jankvisor audio server
      ansible.builtin.include_role:
        name: setup_jankvisor_audio_server

    - name: Setup private ssh keys
      ansible.builtin.include_role:
        name: setup_private_ssh_keys

    - name: Install packer
      ansible.builtin.include_role:
        name: install_packer
