usbinfo:
  primary:
    usb0: "5-2.1"
    usb1: "5-2.2"
    usb2: "5-2.3"
  secondary:
    usb0: "5-1.1"
    usb1: "5-1.2"
    usb2: "5-1.3"

pcieinfo:
  primary:
    hostpci0: "0000:03:00"
  secondary:
    hostpci0: "0000:0a:00"

networkinfo:
  net0: "bridge=vmbr0,firewall=1,tag=70"
  net1: "bridge=vmbr0,firewall=1,tag=10"
  net2: "bridge=vmbr0,firewall=1"

memoryinfo:
  primary: 12000
  secondary: 16000
  