- name: Run post clone
  when: ansible_facts['nodename'] != hostname
  become: true
  block:
    - name: Update /etc/hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        regexp: '^(127.0.1.1.*)$'
        line: "127.0.1.1\t{{ hostname }}.{{ domain }}\t{{ hostname }}" # noqa no-tabs

    - name: Reset machine ID # noqa no-free-form
      ansible.builtin.shell:
        cmd: |
          rm -f /etc/machine-id /var/lib/dbus/machine-id &&
          dbus-uuidgen --ensure=/etc/machine-id &&
          dbus-uuidgen --ensure
      changed_when: true

    - name: Perform os dependent config
      ansible.builtin.include_tasks:
        file: "{{ distro }}.yml"

    - name: Set hostname
      ansible.builtin.hostname:
        name: "{{ hostname }}"
        use: systemd
      notify: reboot vm

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
